// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package face_swap

import (
	types "github.com/magichourhq/magic-hour-go/types"
)

type CreateRequest struct {
	Data types.PostV1FaceSwapBody `json:"data"`
}
