// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package image_projects

// DeleteRequest
type DeleteRequest struct {
	Id string `json:"id"`
}

// GetRequest
type GetRequest struct {
	Id string `json:"id"`
}
