// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// DeleteV1ImageProjectsIdResponse401MessageEnum
type DeleteV1ImageProjectsIdResponse401MessageEnum string

const (
	DeleteV1ImageProjectsIdResponse401MessageEnumUnauthorized DeleteV1ImageProjectsIdResponse401MessageEnum = "Unauthorized"
)
