// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Requested resource is not found
type DeleteV1ImageProjectsIdResponse404 struct {
	Message DeleteV1ImageProjectsIdResponse404MessageEnum `json:"message"`
}
