// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Requested resource is not found
type DeleteV1VideoProjectsIdResponse404 struct {
	Message DeleteV1VideoProjectsIdResponse404MessageEnum `json:"message"`
}
