package types

// DeleteV1VideoProjectsIdResponse401MessageEnum
type DeleteV1VideoProjectsIdResponse401MessageEnum string

const (
	DeleteV1VideoProjectsIdResponse401MessageEnumUnauthorized DeleteV1VideoProjectsIdResponse401MessageEnum = "Unauthorized"
)
