// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type DeleteV1ImageProjectsIdResponse401 struct {
	Message DeleteV1ImageProjectsIdResponse401MessageEnum `json:"message"`
}
