// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// DeleteV1VideoProjectsIdResponse404MessageEnum
type DeleteV1VideoProjectsIdResponse404MessageEnum string

const (
	DeleteV1VideoProjectsIdResponse404MessageEnumNotFound DeleteV1VideoProjectsIdResponse404MessageEnum = "Not Found"
)
