// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// DeleteV1ImageProjectsIdResponse404MessageEnum
type DeleteV1ImageProjectsIdResponse404MessageEnum string

const (
	DeleteV1ImageProjectsIdResponse404MessageEnumNotFound DeleteV1ImageProjectsIdResponse404MessageEnum = "Not Found"
)
