// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type DeleteV1VideoProjectsIdResponse401 struct {
	Message DeleteV1VideoProjectsIdResponse401MessageEnum `json:"message"`
}
