// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type GetV1ImageProjectsIdResponse404MessageEnum string

const (
	GetV1ImageProjectsIdResponse404MessageEnumNotFound GetV1ImageProjectsIdResponse404MessageEnum = "Not Found"
)
