// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type GetV1VideoProjectsIdResponse401MessageEnum string

const (
	GetV1VideoProjectsIdResponse401MessageEnumUnauthorized GetV1VideoProjectsIdResponse401MessageEnum = "Unauthorized"
)
