// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
)

type GetV1ImageProjectsIdResponse struct {
	CreatedAt      string                                      `json:"created_at"`
	Downloads      []GetV1ImageProjectsIdResponseDownloadsItem `json:"downloads"`
	Id             string                                      `json:"id"`
	ImageCount     float64                                     `json:"image_count"`
	Name           nullable.Nullable[string]                   `json:"name"`
	Status         GetV1ImageProjectsIdResponseStatusEnum      `json:"status"`
	TotalFrameCost float64                                     `json:"total_frame_cost"`
	Type           GetV1ImageProjectsIdResponseTypeEnum        `json:"type"`
}
