// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// GetV1ImageProjectsIdResponse401MessageEnum
type GetV1ImageProjectsIdResponse401MessageEnum string

const (
	GetV1ImageProjectsIdResponse401MessageEnumUnauthorized GetV1ImageProjectsIdResponse401MessageEnum = "Unauthorized"
)
