package types

// GetV1VideoProjectsIdResponse401MessageEnum
type GetV1VideoProjectsIdResponse401MessageEnum string

const (
	GetV1VideoProjectsIdResponse401MessageEnumUnauthorized GetV1VideoProjectsIdResponse401MessageEnum = "Unauthorized"
)
