// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// GetV1VideoProjectsIdResponse404MessageEnum
type GetV1VideoProjectsIdResponse404MessageEnum string

const (
	GetV1VideoProjectsIdResponse404MessageEnumNotFound GetV1VideoProjectsIdResponse404MessageEnum = "Not Found"
)
