// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type GetV1VideoProjectsIdResponse401 struct {
	Message GetV1VideoProjectsIdResponse401MessageEnum `json:"message"`
}
