// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// GetV1ImageProjectsIdResponse404MessageEnum
type GetV1ImageProjectsIdResponse404MessageEnum string

const (
	GetV1ImageProjectsIdResponse404MessageEnumNotFound GetV1ImageProjectsIdResponse404MessageEnum = "Not Found"
)
