// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Requested resource is not found
type GetV1VideoProjectsIdResponse404 struct {
	Message GetV1VideoProjectsIdResponse404MessageEnum `json:"message"`
}
