// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
)

type GetV1VideoProjectsIdResponse struct {
	CreatedAt      string                                                  `json:"created_at"`
	Download       nullable.Nullable[GetV1VideoProjectsIdResponseDownload] `json:"download"`
	EndSeconds     float64                                                 `json:"end_seconds"`
	Fps            float64                                                 `json:"fps"`
	Height         float64                                                 `json:"height"`
	Id             string                                                  `json:"id"`
	Name           nullable.Nullable[string]                               `json:"name"`
	StartSeconds   float64                                                 `json:"start_seconds"`
	Status         GetV1VideoProjectsIdResponseStatusEnum                  `json:"status"`
	TotalFrameCost float64                                                 `json:"total_frame_cost"`
	Type           GetV1VideoProjectsIdResponseTypeEnum                    `json:"type"`
	Width          float64                                                 `json:"width"`
}
