// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type GetV1ImageProjectsIdResponse401 struct {
	Message GetV1ImageProjectsIdResponse401MessageEnum `json:"message"`
}
