// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type PostV1VideoToVideoResponse401 struct {
	Message PostV1VideoToVideoResponse401MessageEnum `json:"message"`
}
