// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1TextToVideoBodyOrientationEnum string

const (
	PostV1TextToVideoBodyOrientationEnumLandscape PostV1TextToVideoBodyOrientationEnum = "landscape"
	PostV1TextToVideoBodyOrientationEnumPortrait  PostV1TextToVideoBodyOrientationEnum = "portrait"
	PostV1TextToVideoBodyOrientationEnumSquare    PostV1TextToVideoBodyOrientationEnum = "square"
)
