// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Requested resource is not found
type PostV1VideoToVideoResponse404 struct {
	Message PostV1VideoToVideoResponse404MessageEnum `json:"message"`
}
