// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Requested resource is not found
type PostV1TextToVideoResponse404 struct {
	Message PostV1TextToVideoResponse404MessageEnum `json:"message"`
}
