// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1FilesUploadUrlsBody
type PostV1FilesUploadUrlsBody struct {
	Items []PostV1FilesUploadUrlsBodyItemsItem `json:"items"`
}
