package types

// PostV1AiPhotoEditorResponse401MessageEnum
type PostV1AiPhotoEditorResponse401MessageEnum string

const (
	PostV1AiPhotoEditorResponse401MessageEnumUnauthorized PostV1AiPhotoEditorResponse401MessageEnum = "Unauthorized"
)
