package types

// The art style of the final output video
type PostV1AnimationBodyStyleArtStyleEnum string

const (
	PostV1AnimationBodyStyleArtStyleEnum3dRender                       PostV1AnimationBodyStyleArtStyleEnum = "3D Render"
	PostV1AnimationBodyStyleArtStyleEnum90sStreets                     PostV1AnimationBodyStyleArtStyleEnum = "90s Streets"
	PostV1AnimationBodyStyleArtStyleEnumAbstractMinimalist             PostV1AnimationBodyStyleArtStyleEnum = "Abstract Minimalist"
	PostV1AnimationBodyStyleArtStyleEnumArcane                         PostV1AnimationBodyStyleArtStyleEnum = "Arcane"
	PostV1AnimationBodyStyleArtStyleEnumArtDeco                        PostV1AnimationBodyStyleArtStyleEnum = "Art Deco"
	PostV1AnimationBodyStyleArtStyleEnumBoldColoredIllustration        PostV1AnimationBodyStyleArtStyleEnum = "Bold Colored Illustration"
	PostV1AnimationBodyStyleArtStyleEnumCinematicLandscape             PostV1AnimationBodyStyleArtStyleEnum = "Cinematic Landscape"
	PostV1AnimationBodyStyleArtStyleEnumCinematicMiyazaki              PostV1AnimationBodyStyleArtStyleEnum = "Cinematic Miyazaki"
	PostV1AnimationBodyStyleArtStyleEnumCosmic                         PostV1AnimationBodyStyleArtStyleEnum = "Cosmic"
	PostV1AnimationBodyStyleArtStyleEnumCubist                         PostV1AnimationBodyStyleArtStyleEnum = "Cubist"
	PostV1AnimationBodyStyleArtStyleEnumCustom                         PostV1AnimationBodyStyleArtStyleEnum = "Custom"
	PostV1AnimationBodyStyleArtStyleEnumCyberpunk                      PostV1AnimationBodyStyleArtStyleEnum = "Cyberpunk"
	PostV1AnimationBodyStyleArtStyleEnumDarkGraphicIllustration        PostV1AnimationBodyStyleArtStyleEnum = "Dark Graphic Illustration"
	PostV1AnimationBodyStyleArtStyleEnumDarkWatercolor                 PostV1AnimationBodyStyleArtStyleEnum = "Dark Watercolor"
	PostV1AnimationBodyStyleArtStyleEnumDirectedByAi                   PostV1AnimationBodyStyleArtStyleEnum = "Directed by AI"
	PostV1AnimationBodyStyleArtStyleEnumDoubleExposure                 PostV1AnimationBodyStyleArtStyleEnum = "Double Exposure"
	PostV1AnimationBodyStyleArtStyleEnumFadedIllustration              PostV1AnimationBodyStyleArtStyleEnum = "Faded Illustration"
	PostV1AnimationBodyStyleArtStyleEnumFantasy                        PostV1AnimationBodyStyleArtStyleEnum = "Fantasy"
	PostV1AnimationBodyStyleArtStyleEnumFuturisticAnime                PostV1AnimationBodyStyleArtStyleEnum = "Futuristic Anime"
	PostV1AnimationBodyStyleArtStyleEnumImpressionism                  PostV1AnimationBodyStyleArtStyleEnum = "Impressionism"
	PostV1AnimationBodyStyleArtStyleEnumInkAndWatercolorPortrait       PostV1AnimationBodyStyleArtStyleEnum = "Ink and Watercolor Portrait"
	PostV1AnimationBodyStyleArtStyleEnumInkpunk                        PostV1AnimationBodyStyleArtStyleEnum = "Inkpunk"
	PostV1AnimationBodyStyleArtStyleEnumIntricateAbstractLinesPortrait PostV1AnimationBodyStyleArtStyleEnum = "Intricate Abstract Lines Portrait"
	PostV1AnimationBodyStyleArtStyleEnumJacksonPollock                 PostV1AnimationBodyStyleArtStyleEnum = "Jackson Pollock"
	PostV1AnimationBodyStyleArtStyleEnumLandscapePainting              PostV1AnimationBodyStyleArtStyleEnum = "Landscape Painting"
	PostV1AnimationBodyStyleArtStyleEnumLowPoly                        PostV1AnimationBodyStyleArtStyleEnum = "Low Poly"
	PostV1AnimationBodyStyleArtStyleEnumMiniatures                     PostV1AnimationBodyStyleArtStyleEnum = "Miniatures"
	PostV1AnimationBodyStyleArtStyleEnumMinimalColdFuturism            PostV1AnimationBodyStyleArtStyleEnum = "Minimal Cold Futurism"
	PostV1AnimationBodyStyleArtStyleEnumOilPainting                    PostV1AnimationBodyStyleArtStyleEnum = "Oil Painting"
	PostV1AnimationBodyStyleArtStyleEnumOldSchoolComic                 PostV1AnimationBodyStyleArtStyleEnum = "Old School Comic"
	PostV1AnimationBodyStyleArtStyleEnumOvergrown                      PostV1AnimationBodyStyleArtStyleEnum = "Overgrown"
	PostV1AnimationBodyStyleArtStyleEnumPaintedCityscape               PostV1AnimationBodyStyleArtStyleEnum = "Painted Cityscape"
	PostV1AnimationBodyStyleArtStyleEnumPainterlyIllustration          PostV1AnimationBodyStyleArtStyleEnum = "Painterly Illustration"
	PostV1AnimationBodyStyleArtStyleEnumPhotograph                     PostV1AnimationBodyStyleArtStyleEnum = "Photograph"
	PostV1AnimationBodyStyleArtStyleEnumPixar                          PostV1AnimationBodyStyleArtStyleEnum = "Pixar"
	PostV1AnimationBodyStyleArtStyleEnumPixelArt                       PostV1AnimationBodyStyleArtStyleEnum = "Pixel Art"
	PostV1AnimationBodyStyleArtStyleEnumPostapocalyptic                PostV1AnimationBodyStyleArtStyleEnum = "Postapocalyptic"
	PostV1AnimationBodyStyleArtStyleEnumSinCity                        PostV1AnimationBodyStyleArtStyleEnum = "Sin City"
	PostV1AnimationBodyStyleArtStyleEnumSoftDelicateMattePortrait      PostV1AnimationBodyStyleArtStyleEnum = "Soft Delicate Matte Portrait"
	PostV1AnimationBodyStyleArtStyleEnumSpooky                         PostV1AnimationBodyStyleArtStyleEnum = "Spooky"
	PostV1AnimationBodyStyleArtStyleEnumStudioGhibliFilmStill          PostV1AnimationBodyStyleArtStyleEnum = "Studio Ghibli Film Still"
	PostV1AnimationBodyStyleArtStyleEnumSynthwave                      PostV1AnimationBodyStyleArtStyleEnum = "Synthwave"
	PostV1AnimationBodyStyleArtStyleEnumTraditionalWatercolor          PostV1AnimationBodyStyleArtStyleEnum = "Traditional Watercolor"
	PostV1AnimationBodyStyleArtStyleEnumVanGogh                        PostV1AnimationBodyStyleArtStyleEnum = "Van Gogh"
	PostV1AnimationBodyStyleArtStyleEnumVibrantMatteIllustration       PostV1AnimationBodyStyleArtStyleEnum = "Vibrant Matte Illustration"
	PostV1AnimationBodyStyleArtStyleEnumVintageJapaneseAnime           PostV1AnimationBodyStyleArtStyleEnum = "Vintage Japanese Anime"
	PostV1AnimationBodyStyleArtStyleEnumWoodcut                        PostV1AnimationBodyStyleArtStyleEnum = "Woodcut"
)
