// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1AiHeadshotGeneratorResponse401MessageEnum string

const (
	PostV1AiHeadshotGeneratorResponse401MessageEnumUnauthorized PostV1AiHeadshotGeneratorResponse401MessageEnum = "Unauthorized"
)
