// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1FaceSwapPhotoResponse404MessageEnum
type PostV1FaceSwapPhotoResponse404MessageEnum string

const (
	PostV1FaceSwapPhotoResponse404MessageEnumNotFound PostV1FaceSwapPhotoResponse404MessageEnum = "Not Found"
)
