package types

// PostV1AiQrCodeGeneratorResponse401MessageEnum
type PostV1AiQrCodeGeneratorResponse401MessageEnum string

const (
	PostV1AiQrCodeGeneratorResponse401MessageEnumUnauthorized PostV1AiQrCodeGeneratorResponse401MessageEnum = "Unauthorized"
)
