// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1AiQrCodeGeneratorResponse404MessageEnum
type PostV1AiQrCodeGeneratorResponse404MessageEnum string

const (
	PostV1AiQrCodeGeneratorResponse404MessageEnumNotFound PostV1AiQrCodeGeneratorResponse404MessageEnum = "Not Found"
)
