// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1AiImageGeneratorBodyStyle
type PostV1AiImageGeneratorBodyStyle struct {
	// The prompt used for the image.
	Prompt string `json:"prompt"`
}
