// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1AiImageGeneratorResponse401MessageEnum
type PostV1AiImageGeneratorResponse401MessageEnum string

const (
	PostV1AiImageGeneratorResponse401MessageEnumUnauthorized PostV1AiImageGeneratorResponse401MessageEnum = "Unauthorized"
)
