// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1VideoToVideoBodyStylePromptTypeEnum string

const (
	PostV1VideoToVideoBodyStylePromptTypeEnumAppendDefault PostV1VideoToVideoBodyStylePromptTypeEnum = "append_default"
	PostV1VideoToVideoBodyStylePromptTypeEnumCustom        PostV1VideoToVideoBodyStylePromptTypeEnum = "custom"
	PostV1VideoToVideoBodyStylePromptTypeEnumDefault       PostV1VideoToVideoBodyStylePromptTypeEnum = "default"
)
