// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1FilesUploadUrlsResponseItemsItem struct {
	ExpiresAt string `json:"expires_at"`
	FilePath  string `json:"file_path"`
	UploadUrl string `json:"upload_url"`
}
