// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Success
type PostV1FaceSwapResponse struct {
	// Estimated cost of the video in terms of number of frames needed to render the video. Frames will be adjusted when the video completes
	EstimatedFrameCost int `json:"estimated_frame_cost"`
	// Unique ID of the image. This value can be used in the [get image project API](/api/tag/image-projects/get/v1/image-projects/{id}) to fetch additional details such as status
	Id string `json:"id"`
}
