// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1FilesUploadUrlsBodyItemsItemTypeEnum string

const (
	PostV1FilesUploadUrlsBodyItemsItemTypeEnumAudio PostV1FilesUploadUrlsBodyItemsItemTypeEnum = "audio"
	PostV1FilesUploadUrlsBodyItemsItemTypeEnumImage PostV1FilesUploadUrlsBodyItemsItemTypeEnum = "image"
	PostV1FilesUploadUrlsBodyItemsItemTypeEnumVideo PostV1FilesUploadUrlsBodyItemsItemTypeEnum = "video"
)
