// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1TextToVideoResponse struct {
	EstimatedFrameCost float64 `json:"estimated_frame_cost"`
	Id                 string  `json:"id"`
}
