// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1AiHeadshotGeneratorResponse404MessageEnum
type PostV1AiHeadshotGeneratorResponse404MessageEnum string

const (
	PostV1AiHeadshotGeneratorResponse404MessageEnumNotFound PostV1AiHeadshotGeneratorResponse404MessageEnum = "Not Found"
)
