// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1FaceSwapResponse404MessageEnum
type PostV1FaceSwapResponse404MessageEnum string

const (
	PostV1FaceSwapResponse404MessageEnumNotFound PostV1FaceSwapResponse404MessageEnum = "Not Found"
)
