// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1AiImageUpscalerResponse401MessageEnum
type PostV1AiImageUpscalerResponse401MessageEnum string

const (
	PostV1AiImageUpscalerResponse401MessageEnumUnauthorized PostV1AiImageUpscalerResponse401MessageEnum = "Unauthorized"
)
