// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type PostV1FaceSwapPhotoResponse401 struct {
	Message PostV1FaceSwapPhotoResponse401MessageEnum `json:"message"`
}
