// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1VideoToVideoResponse404MessageEnum
type PostV1VideoToVideoResponse404MessageEnum string

const (
	PostV1VideoToVideoResponse404MessageEnumNotFound PostV1VideoToVideoResponse404MessageEnum = "Not Found"
)
