// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1FaceSwapPhotoResponse401MessageEnum
type PostV1FaceSwapPhotoResponse401MessageEnum string

const (
	PostV1FaceSwapPhotoResponse401MessageEnumUnauthorized PostV1FaceSwapPhotoResponse401MessageEnum = "Unauthorized"
)
