// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
)

type PostV1AiImageUpscalerBodyStyle struct {
	Enhancement PostV1AiImageUpscalerBodyStyleEnhancementEnum `json:"enhancement"`
	Prompt      nullable.Nullable[string]                     `json:"prompt,omitempty"`
}
