// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1FaceSwapPhotoBodyAssets struct {
	SourceFilePath string `json:"source_file_path"`
	TargetFilePath string `json:"target_file_path"`
}
