// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1AiImageGeneratorBodyOrientationEnum
type PostV1AiImageGeneratorBodyOrientationEnum string

const (
	PostV1AiImageGeneratorBodyOrientationEnumLandscape PostV1AiImageGeneratorBodyOrientationEnum = "landscape"
	PostV1AiImageGeneratorBodyOrientationEnumPortrait  PostV1AiImageGeneratorBodyOrientationEnum = "portrait"
	PostV1AiImageGeneratorBodyOrientationEnumSquare    PostV1AiImageGeneratorBodyOrientationEnum = "square"
)
