// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type PostV1ImageToVideoResponse401 struct {
	Message PostV1ImageToVideoResponse401MessageEnum `json:"message"`
}
