// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Requested resource is not found
type PostV1LipSyncResponse404 struct {
	Message PostV1LipSyncResponse404MessageEnum `json:"message"`
}
