// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
)

type PostV1TextToVideoBody struct {
	EndSeconds  float64                              `json:"end_seconds"`
	Name        nullable.Nullable[string]            `json:"name"`
	Orientation PostV1TextToVideoBodyOrientationEnum `json:"orientation"`
	Style       PostV1TextToVideoBodyStyle           `json:"style"`
}
