// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1ImageToVideoResponse404MessageEnum string

const (
	PostV1ImageToVideoResponse404MessageEnumNotFound PostV1ImageToVideoResponse404MessageEnum = "Not Found"
)
