// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1ImageToVideoResponse401MessageEnum
type PostV1ImageToVideoResponse401MessageEnum string

const (
	PostV1ImageToVideoResponse401MessageEnumUnauthorized PostV1ImageToVideoResponse401MessageEnum = "Unauthorized"
)
