// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Requested resource is not found
type PostV1AiPhotoEditorResponse404 struct {
	Message PostV1AiPhotoEditorResponse404MessageEnum `json:"message"`
}
