// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type PostV1AiHeadshotGeneratorResponse401 struct {
	Message PostV1AiHeadshotGeneratorResponse401MessageEnum `json:"message"`
}
