// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
)

type PostV1FaceSwapBody struct {
	Assets       PostV1FaceSwapBodyAssets  `json:"assets"`
	EndSeconds   float64                   `json:"end_seconds"`
	Height       float64                   `json:"height"`
	Name         nullable.Nullable[string] `json:"name"`
	StartSeconds float64                   `json:"start_seconds"`
	Width        float64                   `json:"width"`
}
