// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1TextToVideoResponse401MessageEnum
type PostV1TextToVideoResponse401MessageEnum string

const (
	PostV1TextToVideoResponse401MessageEnumUnauthorized PostV1TextToVideoResponse401MessageEnum = "Unauthorized"
)
