// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1AiImageGeneratorResponse404MessageEnum string

const (
	PostV1AiImageGeneratorResponse404MessageEnumNotFound PostV1AiImageGeneratorResponse404MessageEnum = "Not Found"
)
