// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
)

type PostV1ImageToVideoBody struct {
	Assets     PostV1ImageToVideoBodyAssets `json:"assets"`
	EndSeconds float64                      `json:"end_seconds"`
	Height     float64                      `json:"height"`
	Name       nullable.Nullable[string]    `json:"name"`
	Style      PostV1ImageToVideoBodyStyle  `json:"style"`
	Width      float64                      `json:"width"`
}
