// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1VideoToVideoBodyStyleVersionEnum string

const (
	PostV1VideoToVideoBodyStyleVersionEnumDefault PostV1VideoToVideoBodyStyleVersionEnum = "default"
	PostV1VideoToVideoBodyStyleVersionEnumV1      PostV1VideoToVideoBodyStyleVersionEnum = "v1"
	PostV1VideoToVideoBodyStyleVersionEnumV2      PostV1VideoToVideoBodyStyleVersionEnum = "v2"
)
