// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Requested resource is not found
type PostV1AiHeadshotGeneratorResponse404 struct {
	Message PostV1AiHeadshotGeneratorResponse404MessageEnum `json:"message"`
}
