package types

// PostV1AiImageUpscalerBodyStyleEnhancementEnum
type PostV1AiImageUpscalerBodyStyleEnhancementEnum string

const (
	PostV1AiImageUpscalerBodyStyleEnhancementEnumBalanced    PostV1AiImageUpscalerBodyStyleEnhancementEnum = "Balanced"
	PostV1AiImageUpscalerBodyStyleEnhancementEnumCreative    PostV1AiImageUpscalerBodyStyleEnhancementEnum = "Creative"
	PostV1AiImageUpscalerBodyStyleEnhancementEnumResemblance PostV1AiImageUpscalerBodyStyleEnhancementEnum = "Resemblance"
)
