// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1VideoToVideoResponse401MessageEnum string

const (
	PostV1VideoToVideoResponse401MessageEnumUnauthorized PostV1VideoToVideoResponse401MessageEnum = "Unauthorized"
)
