// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1TextToVideoResponse404MessageEnum
type PostV1TextToVideoResponse404MessageEnum string

const (
	PostV1TextToVideoResponse404MessageEnumNotFound PostV1TextToVideoResponse404MessageEnum = "Not Found"
)
