// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type PostV1AiQrCodeGeneratorResponse401 struct {
	Message PostV1AiQrCodeGeneratorResponse401MessageEnum `json:"message"`
}
