// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Requested resource is not found
type PostV1ImageToVideoResponse404 struct {
	Message PostV1ImageToVideoResponse404MessageEnum `json:"message"`
}
