// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Success
type PostV1AnimationResponse struct {
	// Estimated cost of the video in terms of number of frames needed to render the video. Frames will be adjusted when the video completes
	EstimatedFrameCost int `json:"estimated_frame_cost"`
	// Unique ID of the video. This value can be used in the [get video project API](/api/tag/video-projects/get/v1/video-projects/{id}) to fetch additional details such as status
	Id string `json:"id"`
}
