// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
)

type PostV1LipSyncBodyAssets struct {
	AudioFilePath string                                 `json:"audio_file_path"`
	VideoFilePath nullable.Nullable[string]              `json:"video_file_path,omitempty"`
	VideoSource   PostV1LipSyncBodyAssetsVideoSourceEnum `json:"video_source"`
	YoutubeUrl    nullable.Nullable[string]              `json:"youtube_url,omitempty"`
}
