// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1ImageBackgroundRemoverResponse404MessageEnum
type PostV1ImageBackgroundRemoverResponse404MessageEnum string

const (
	PostV1ImageBackgroundRemoverResponse404MessageEnumNotFound PostV1ImageBackgroundRemoverResponse404MessageEnum = "Not Found"
)
