// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type PostV1AiImageUpscalerResponse401 struct {
	Message PostV1AiImageUpscalerResponse401MessageEnum `json:"message"`
}
