// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type PostV1ImageBackgroundRemoverResponse401 struct {
	Message PostV1ImageBackgroundRemoverResponse401MessageEnum `json:"message"`
}
