// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1FaceSwapBodyAssetsVideoSourceEnum
type PostV1FaceSwapBodyAssetsVideoSourceEnum string

const (
	PostV1FaceSwapBodyAssetsVideoSourceEnumFile    PostV1FaceSwapBodyAssetsVideoSourceEnum = "file"
	PostV1FaceSwapBodyAssetsVideoSourceEnumYoutube PostV1FaceSwapBodyAssetsVideoSourceEnum = "youtube"
)
