// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1FilesUploadUrlsResponse404MessageEnum
type PostV1FilesUploadUrlsResponse404MessageEnum string

const (
	PostV1FilesUploadUrlsResponse404MessageEnumNotFound PostV1FilesUploadUrlsResponse404MessageEnum = "Not Found"
)
