// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1VideoToVideoBodyStyleModelEnum string

const (
	PostV1VideoToVideoBodyStyleModelEnumAbsoluteReality PostV1VideoToVideoBodyStyleModelEnum = "Absolute Reality"
	PostV1VideoToVideoBodyStyleModelEnumDreamshaper     PostV1VideoToVideoBodyStyleModelEnum = "Dreamshaper"
	PostV1VideoToVideoBodyStyleModelEnumFlat2dAnime     PostV1VideoToVideoBodyStyleModelEnum = "Flat 2D Anime"
	PostV1VideoToVideoBodyStyleModelEnumDefault         PostV1VideoToVideoBodyStyleModelEnum = "default"
)
