// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Requested resource is not found
type PostV1AnimationResponse404 struct {
	Message PostV1AnimationResponse404MessageEnum `json:"message"`
}
