// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
)

type PostV1ImageToVideoBodyStyle struct {
	Prompt nullable.Nullable[string] `json:"prompt"`
}
