// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Requested resource is not found
type PostV1FilesUploadUrlsResponse404 struct {
	Message PostV1FilesUploadUrlsResponse404MessageEnum `json:"message"`
}
