// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
)

type PostV1VideoToVideoBodyStyle struct {
	ArtStyle   PostV1VideoToVideoBodyStyleArtStyleEnum   `json:"art_style"`
	Model      PostV1VideoToVideoBodyStyleModelEnum      `json:"model"`
	Prompt     nullable.Nullable[string]                 `json:"prompt"`
	PromptType PostV1VideoToVideoBodyStylePromptTypeEnum `json:"prompt_type"`
	Version    PostV1VideoToVideoBodyStyleVersionEnum    `json:"version"`
}
