// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1FilesUploadUrlsBodyItemsItem struct {
	Extension string                                     `json:"extension"`
	Type      PostV1FilesUploadUrlsBodyItemsItemTypeEnum `json:"type"`
}
