// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type PostV1AiImageGeneratorResponse401 struct {
	Message PostV1AiImageGeneratorResponse401MessageEnum `json:"message"`
}
