// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1FilesUploadUrlsResponse401MessageEnum string

const (
	PostV1FilesUploadUrlsResponse401MessageEnumUnauthorized PostV1FilesUploadUrlsResponse401MessageEnum = "Unauthorized"
)
