// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1TextToVideoBodyStyle
type PostV1TextToVideoBodyStyle struct {
	// The prompt used for the video.
	Prompt string `json:"prompt"`
}
