// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
)

type PostV1VideoToVideoBodyAssets struct {
	VideoFilePath nullable.Nullable[string]                   `json:"video_file_path,omitempty"`
	VideoSource   PostV1VideoToVideoBodyAssetsVideoSourceEnum `json:"video_source"`
	YoutubeUrl    nullable.Nullable[string]                   `json:"youtube_url,omitempty"`
}
