// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Requested resource is not found
type PostV1ImageBackgroundRemoverResponse404 struct {
	Message PostV1ImageBackgroundRemoverResponse404MessageEnum `json:"message"`
}
