// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1AnimationResponse404MessageEnum
type PostV1AnimationResponse404MessageEnum string

const (
	PostV1AnimationResponse404MessageEnumNotFound PostV1AnimationResponse404MessageEnum = "Not Found"
)
