// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
)

type PostV1VideoToVideoBody struct {
	Assets        PostV1VideoToVideoBodyAssets                               `json:"assets"`
	EndSeconds    float64                                                    `json:"end_seconds"`
	FpsResolution nullable.Nullable[PostV1VideoToVideoBodyFpsResolutionEnum] `json:"fps_resolution,omitempty"`
	Height        float64                                                    `json:"height"`
	Name          nullable.Nullable[string]                                  `json:"name"`
	StartSeconds  float64                                                    `json:"start_seconds"`
	Style         PostV1VideoToVideoBodyStyle                                `json:"style"`
	Width         float64                                                    `json:"width"`
}
