// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1LipSyncResponse404MessageEnum
type PostV1LipSyncResponse404MessageEnum string

const (
	PostV1LipSyncResponse404MessageEnumNotFound PostV1LipSyncResponse404MessageEnum = "Not Found"
)
