// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1AiImageUpscalerResponse404MessageEnum string

const (
	PostV1AiImageUpscalerResponse404MessageEnumNotFound PostV1AiImageUpscalerResponse404MessageEnum = "Not Found"
)
