// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1VideoToVideoBodyAssetsVideoSourceEnum
type PostV1VideoToVideoBodyAssetsVideoSourceEnum string

const (
	PostV1VideoToVideoBodyAssetsVideoSourceEnumFile    PostV1VideoToVideoBodyAssetsVideoSourceEnum = "file"
	PostV1VideoToVideoBodyAssetsVideoSourceEnumYoutube PostV1VideoToVideoBodyAssetsVideoSourceEnum = "youtube"
)
