// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1VideoToVideoBodyFpsResolutionEnum string

const (
	PostV1VideoToVideoBodyFpsResolutionEnumFull PostV1VideoToVideoBodyFpsResolutionEnum = "FULL"
	PostV1VideoToVideoBodyFpsResolutionEnumHalf PostV1VideoToVideoBodyFpsResolutionEnum = "HALF"
)
