// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Requested resource is not found
type PostV1FaceSwapResponse404 struct {
	Message PostV1FaceSwapResponse404MessageEnum `json:"message"`
}
