// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type PostV1FilesUploadUrlsResponse401 struct {
	Message PostV1FilesUploadUrlsResponse401MessageEnum `json:"message"`
}
