// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
)

type PostV1AiImageGeneratorBody struct {
	ImageCount  float64                                   `json:"image_count"`
	Name        nullable.Nullable[string]                 `json:"name,omitempty"`
	Orientation PostV1AiImageGeneratorBodyOrientationEnum `json:"orientation"`
	Style       PostV1AiImageGeneratorBodyStyle           `json:"style"`
}
