// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// The request is not properly authenticated
type PostV1TextToVideoResponse401 struct {
	Message PostV1TextToVideoResponse401MessageEnum `json:"message"`
}
