// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
)

type PostV1AiImageUpscalerBody struct {
	Assets      PostV1AiImageUpscalerBodyAssets `json:"assets"`
	Name        nullable.Nullable[string]       `json:"name,omitempty"`
	ScaleFactor float64                         `json:"scale_factor"`
	Style       PostV1AiImageUpscalerBodyStyle  `json:"style"`
}
