// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1FaceSwapResponse401MessageEnum string

const (
	PostV1FaceSwapResponse401MessageEnumUnauthorized PostV1FaceSwapResponse401MessageEnum = "Unauthorized"
)
