// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

type PostV1LipSyncBodyAssetsVideoSourceEnum string

const (
	PostV1LipSyncBodyAssetsVideoSourceEnumFile    PostV1LipSyncBodyAssetsVideoSourceEnum = "file"
	PostV1LipSyncBodyAssetsVideoSourceEnumYoutube PostV1LipSyncBodyAssetsVideoSourceEnum = "youtube"
)
