// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// Success
type PostV1FaceSwapPhotoResponse struct {
	FrameCost int `json:"frame_cost"`
	// Unique ID of the image. This value can be used in the [get image project API](/api/tag/image-projects/get/v1/image-projects/{id}) to fetch additional details such as status
	Id string `json:"id"`
}
