// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package types

// PostV1AiQrCodeGeneratorResponse401MessageEnum
type PostV1AiQrCodeGeneratorResponse401MessageEnum string

const (
	PostV1AiQrCodeGeneratorResponse401MessageEnumUnauthorized PostV1AiQrCodeGeneratorResponse401MessageEnum = "Unauthorized"
)
