package types

// The art style of the final output video
type V1AnimationCreateBodyStyleArtStyleEnum string

const (
	V1AnimationCreateBodyStyleArtStyleEnum3dRender                       V1AnimationCreateBodyStyleArtStyleEnum = "3D Render"
	V1AnimationCreateBodyStyleArtStyleEnum90sStreets                     V1AnimationCreateBodyStyleArtStyleEnum = "90s Streets"
	V1AnimationCreateBodyStyleArtStyleEnumAbstractMinimalist             V1AnimationCreateBodyStyleArtStyleEnum = "Abstract Minimalist"
	V1AnimationCreateBodyStyleArtStyleEnumArcane                         V1AnimationCreateBodyStyleArtStyleEnum = "Arcane"
	V1AnimationCreateBodyStyleArtStyleEnumArtDeco                        V1AnimationCreateBodyStyleArtStyleEnum = "Art Deco"
	V1AnimationCreateBodyStyleArtStyleEnumBoldColoredIllustration        V1AnimationCreateBodyStyleArtStyleEnum = "Bold Colored Illustration"
	V1AnimationCreateBodyStyleArtStyleEnumCinematicLandscape             V1AnimationCreateBodyStyleArtStyleEnum = "Cinematic Landscape"
	V1AnimationCreateBodyStyleArtStyleEnumCinematicMiyazaki              V1AnimationCreateBodyStyleArtStyleEnum = "Cinematic Miyazaki"
	V1AnimationCreateBodyStyleArtStyleEnumCosmic                         V1AnimationCreateBodyStyleArtStyleEnum = "Cosmic"
	V1AnimationCreateBodyStyleArtStyleEnumCubist                         V1AnimationCreateBodyStyleArtStyleEnum = "Cubist"
	V1AnimationCreateBodyStyleArtStyleEnumCustom                         V1AnimationCreateBodyStyleArtStyleEnum = "Custom"
	V1AnimationCreateBodyStyleArtStyleEnumCyberpunk                      V1AnimationCreateBodyStyleArtStyleEnum = "Cyberpunk"
	V1AnimationCreateBodyStyleArtStyleEnumDarkGraphicIllustration        V1AnimationCreateBodyStyleArtStyleEnum = "Dark Graphic Illustration"
	V1AnimationCreateBodyStyleArtStyleEnumDarkWatercolor                 V1AnimationCreateBodyStyleArtStyleEnum = "Dark Watercolor"
	V1AnimationCreateBodyStyleArtStyleEnumDirectedByAi                   V1AnimationCreateBodyStyleArtStyleEnum = "Directed by AI"
	V1AnimationCreateBodyStyleArtStyleEnumDoubleExposure                 V1AnimationCreateBodyStyleArtStyleEnum = "Double Exposure"
	V1AnimationCreateBodyStyleArtStyleEnumFadedIllustration              V1AnimationCreateBodyStyleArtStyleEnum = "Faded Illustration"
	V1AnimationCreateBodyStyleArtStyleEnumFantasy                        V1AnimationCreateBodyStyleArtStyleEnum = "Fantasy"
	V1AnimationCreateBodyStyleArtStyleEnumFuturisticAnime                V1AnimationCreateBodyStyleArtStyleEnum = "Futuristic Anime"
	V1AnimationCreateBodyStyleArtStyleEnumImpressionism                  V1AnimationCreateBodyStyleArtStyleEnum = "Impressionism"
	V1AnimationCreateBodyStyleArtStyleEnumInkAndWatercolorPortrait       V1AnimationCreateBodyStyleArtStyleEnum = "Ink and Watercolor Portrait"
	V1AnimationCreateBodyStyleArtStyleEnumInkpunk                        V1AnimationCreateBodyStyleArtStyleEnum = "Inkpunk"
	V1AnimationCreateBodyStyleArtStyleEnumIntricateAbstractLinesPortrait V1AnimationCreateBodyStyleArtStyleEnum = "Intricate Abstract Lines Portrait"
	V1AnimationCreateBodyStyleArtStyleEnumJacksonPollock                 V1AnimationCreateBodyStyleArtStyleEnum = "Jackson Pollock"
	V1AnimationCreateBodyStyleArtStyleEnumLandscapePainting              V1AnimationCreateBodyStyleArtStyleEnum = "Landscape Painting"
	V1AnimationCreateBodyStyleArtStyleEnumLowPoly                        V1AnimationCreateBodyStyleArtStyleEnum = "Low Poly"
	V1AnimationCreateBodyStyleArtStyleEnumMiniatures                     V1AnimationCreateBodyStyleArtStyleEnum = "Miniatures"
	V1AnimationCreateBodyStyleArtStyleEnumMinimalColdFuturism            V1AnimationCreateBodyStyleArtStyleEnum = "Minimal Cold Futurism"
	V1AnimationCreateBodyStyleArtStyleEnumOilPainting                    V1AnimationCreateBodyStyleArtStyleEnum = "Oil Painting"
	V1AnimationCreateBodyStyleArtStyleEnumOldSchoolComic                 V1AnimationCreateBodyStyleArtStyleEnum = "Old School Comic"
	V1AnimationCreateBodyStyleArtStyleEnumOvergrown                      V1AnimationCreateBodyStyleArtStyleEnum = "Overgrown"
	V1AnimationCreateBodyStyleArtStyleEnumPaintedCityscape               V1AnimationCreateBodyStyleArtStyleEnum = "Painted Cityscape"
	V1AnimationCreateBodyStyleArtStyleEnumPainterlyIllustration          V1AnimationCreateBodyStyleArtStyleEnum = "Painterly Illustration"
	V1AnimationCreateBodyStyleArtStyleEnumPhotograph                     V1AnimationCreateBodyStyleArtStyleEnum = "Photograph"
	V1AnimationCreateBodyStyleArtStyleEnumPixar                          V1AnimationCreateBodyStyleArtStyleEnum = "Pixar"
	V1AnimationCreateBodyStyleArtStyleEnumPixelArt                       V1AnimationCreateBodyStyleArtStyleEnum = "Pixel Art"
	V1AnimationCreateBodyStyleArtStyleEnumPostapocalyptic                V1AnimationCreateBodyStyleArtStyleEnum = "Postapocalyptic"
	V1AnimationCreateBodyStyleArtStyleEnumSinCity                        V1AnimationCreateBodyStyleArtStyleEnum = "Sin City"
	V1AnimationCreateBodyStyleArtStyleEnumSoftDelicateMattePortrait      V1AnimationCreateBodyStyleArtStyleEnum = "Soft Delicate Matte Portrait"
	V1AnimationCreateBodyStyleArtStyleEnumSpooky                         V1AnimationCreateBodyStyleArtStyleEnum = "Spooky"
	V1AnimationCreateBodyStyleArtStyleEnumStudioGhibliFilmStill          V1AnimationCreateBodyStyleArtStyleEnum = "Studio Ghibli Film Still"
	V1AnimationCreateBodyStyleArtStyleEnumSynthwave                      V1AnimationCreateBodyStyleArtStyleEnum = "Synthwave"
	V1AnimationCreateBodyStyleArtStyleEnumTraditionalWatercolor          V1AnimationCreateBodyStyleArtStyleEnum = "Traditional Watercolor"
	V1AnimationCreateBodyStyleArtStyleEnumVanGogh                        V1AnimationCreateBodyStyleArtStyleEnum = "Van Gogh"
	V1AnimationCreateBodyStyleArtStyleEnumVibrantMatteIllustration       V1AnimationCreateBodyStyleArtStyleEnum = "Vibrant Matte Illustration"
	V1AnimationCreateBodyStyleArtStyleEnumVintageJapaneseAnime           V1AnimationCreateBodyStyleArtStyleEnum = "Vintage Japanese Anime"
	V1AnimationCreateBodyStyleArtStyleEnumWoodcut                        V1AnimationCreateBodyStyleArtStyleEnum = "Woodcut"
)
