package types

// V1AnimationCreateBodyStyleCameraEffectEnum
type V1AnimationCreateBodyStyleCameraEffectEnum string

const (
	V1AnimationCreateBodyStyleCameraEffectEnumAccelerate                 V1AnimationCreateBodyStyleCameraEffectEnum = "Accelerate"
	V1AnimationCreateBodyStyleCameraEffectEnumAggressiveZoomInAudioSync  V1AnimationCreateBodyStyleCameraEffectEnum = "Aggressive Zoom In - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumAggressiveZoomOutAudioSync V1AnimationCreateBodyStyleCameraEffectEnum = "Aggressive Zoom Out - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumBoostZoomIn                V1AnimationCreateBodyStyleCameraEffectEnum = "Boost Zoom In"
	V1AnimationCreateBodyStyleCameraEffectEnumBoostZoomOut               V1AnimationCreateBodyStyleCameraEffectEnum = "Boost Zoom Out"
	V1AnimationCreateBodyStyleCameraEffectEnumBounceInAndOut             V1AnimationCreateBodyStyleCameraEffectEnum = "Bounce In And Out"
	V1AnimationCreateBodyStyleCameraEffectEnumBounceOut                  V1AnimationCreateBodyStyleCameraEffectEnum = "Bounce Out"
	V1AnimationCreateBodyStyleCameraEffectEnumBounceOutAudioSync         V1AnimationCreateBodyStyleCameraEffectEnum = "Bounce Out - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumBounceAndSpinAudioSync     V1AnimationCreateBodyStyleCameraEffectEnum = "Bounce and Spin - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumBounceInPlace              V1AnimationCreateBodyStyleCameraEffectEnum = "Bounce in Place"
	V1AnimationCreateBodyStyleCameraEffectEnumCogInTheMachine            V1AnimationCreateBodyStyleCameraEffectEnum = "Cog in the Machine"
	V1AnimationCreateBodyStyleCameraEffectEnumDevolveAudioSync           V1AnimationCreateBodyStyleCameraEffectEnum = "Devolve - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumDirectedByAi               V1AnimationCreateBodyStyleCameraEffectEnum = "Directed by AI"
	V1AnimationCreateBodyStyleCameraEffectEnumDramaticZoomIn             V1AnimationCreateBodyStyleCameraEffectEnum = "Dramatic Zoom In"
	V1AnimationCreateBodyStyleCameraEffectEnumDramaticZoomOut            V1AnimationCreateBodyStyleCameraEffectEnum = "Dramatic Zoom Out"
	V1AnimationCreateBodyStyleCameraEffectEnumDriftSpin                  V1AnimationCreateBodyStyleCameraEffectEnum = "Drift Spin"
	V1AnimationCreateBodyStyleCameraEffectEnumEarthquakeBounce           V1AnimationCreateBodyStyleCameraEffectEnum = "Earthquake Bounce"
	V1AnimationCreateBodyStyleCameraEffectEnumEarthquakeBounceAudioSync  V1AnimationCreateBodyStyleCameraEffectEnum = "Earthquake Bounce - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumEvolveAudioSync            V1AnimationCreateBodyStyleCameraEffectEnum = "Evolve - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumHeartbeat                  V1AnimationCreateBodyStyleCameraEffectEnum = "Heartbeat"
	V1AnimationCreateBodyStyleCameraEffectEnumHesitateIn                 V1AnimationCreateBodyStyleCameraEffectEnum = "Hesitate In"
	V1AnimationCreateBodyStyleCameraEffectEnumJump                       V1AnimationCreateBodyStyleCameraEffectEnum = "Jump"
	V1AnimationCreateBodyStyleCameraEffectEnumPanLeft                    V1AnimationCreateBodyStyleCameraEffectEnum = "Pan Left"
	V1AnimationCreateBodyStyleCameraEffectEnumPanRight                   V1AnimationCreateBodyStyleCameraEffectEnum = "Pan Right"
	V1AnimationCreateBodyStyleCameraEffectEnumPulseAudioSync             V1AnimationCreateBodyStyleCameraEffectEnum = "Pulse - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumPusher                     V1AnimationCreateBodyStyleCameraEffectEnum = "Pusher"
	V1AnimationCreateBodyStyleCameraEffectEnumPusherAudioSync            V1AnimationCreateBodyStyleCameraEffectEnum = "Pusher - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumQuadrant                   V1AnimationCreateBodyStyleCameraEffectEnum = "Quadrant"
	V1AnimationCreateBodyStyleCameraEffectEnumRiseAndClimb               V1AnimationCreateBodyStyleCameraEffectEnum = "Rise and Climb"
	V1AnimationCreateBodyStyleCameraEffectEnumRoadTrip                   V1AnimationCreateBodyStyleCameraEffectEnum = "Road Trip"
	V1AnimationCreateBodyStyleCameraEffectEnumRodeo                      V1AnimationCreateBodyStyleCameraEffectEnum = "Rodeo"
	V1AnimationCreateBodyStyleCameraEffectEnumRollIn                     V1AnimationCreateBodyStyleCameraEffectEnum = "Roll In"
	V1AnimationCreateBodyStyleCameraEffectEnumRollInAudioSync            V1AnimationCreateBodyStyleCameraEffectEnum = "Roll In - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumRollingBounces             V1AnimationCreateBodyStyleCameraEffectEnum = "Rolling Bounces"
	V1AnimationCreateBodyStyleCameraEffectEnumRubberBand                 V1AnimationCreateBodyStyleCameraEffectEnum = "Rubber Band"
	V1AnimationCreateBodyStyleCameraEffectEnumSimpleZoomIn               V1AnimationCreateBodyStyleCameraEffectEnum = "Simple Zoom In"
	V1AnimationCreateBodyStyleCameraEffectEnumSimpleZoomOut              V1AnimationCreateBodyStyleCameraEffectEnum = "Simple Zoom Out"
	V1AnimationCreateBodyStyleCameraEffectEnumSliceBounce                V1AnimationCreateBodyStyleCameraEffectEnum = "Slice Bounce"
	V1AnimationCreateBodyStyleCameraEffectEnumSlideshow                  V1AnimationCreateBodyStyleCameraEffectEnum = "Slideshow"
	V1AnimationCreateBodyStyleCameraEffectEnumSpeedOfLight               V1AnimationCreateBodyStyleCameraEffectEnum = "Speed of Light"
	V1AnimationCreateBodyStyleCameraEffectEnumSpinBounce                 V1AnimationCreateBodyStyleCameraEffectEnum = "Spin Bounce"
	V1AnimationCreateBodyStyleCameraEffectEnumSwayOut                    V1AnimationCreateBodyStyleCameraEffectEnum = "Sway Out"
	V1AnimationCreateBodyStyleCameraEffectEnumSwayOutAudioSync           V1AnimationCreateBodyStyleCameraEffectEnum = "Sway Out - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumTiltDown                   V1AnimationCreateBodyStyleCameraEffectEnum = "Tilt Down"
	V1AnimationCreateBodyStyleCameraEffectEnumTiltUp                     V1AnimationCreateBodyStyleCameraEffectEnum = "Tilt Up"
	V1AnimationCreateBodyStyleCameraEffectEnumTraverse                   V1AnimationCreateBodyStyleCameraEffectEnum = "Traverse"
	V1AnimationCreateBodyStyleCameraEffectEnumTron                       V1AnimationCreateBodyStyleCameraEffectEnum = "Tron"
	V1AnimationCreateBodyStyleCameraEffectEnumVertigo                    V1AnimationCreateBodyStyleCameraEffectEnum = "Vertigo"
	V1AnimationCreateBodyStyleCameraEffectEnumVertigoAudioSync           V1AnimationCreateBodyStyleCameraEffectEnum = "Vertigo - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumZoomInAudioSync            V1AnimationCreateBodyStyleCameraEffectEnum = "Zoom In - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumZoomInAndSpinAudioSync     V1AnimationCreateBodyStyleCameraEffectEnum = "Zoom In and Spin - Audio Sync"
	V1AnimationCreateBodyStyleCameraEffectEnumZoomOutAudioSync           V1AnimationCreateBodyStyleCameraEffectEnum = "Zoom Out - Audio Sync"
)
