package types

// V1AiClothesChangerCreateResponse401MessageEnum
type V1AiClothesChangerCreateResponse401MessageEnum string

const (
	V1AiClothesChangerCreateResponse401MessageEnumUnauthorized V1AiClothesChangerCreateResponse401MessageEnum = "Unauthorized"
)
