package types

// V1AiQrCodeGeneratorcreateResponse404MessageEnum
type V1AiQrCodeGeneratorcreateResponse404MessageEnum string

const (
	V1AiQrCodeGeneratorcreateResponse404MessageEnumNotFound V1AiQrCodeGeneratorcreateResponse404MessageEnum = "Not Found"
)
