package types

// V1AiImageUpscalercreateResponse401MessageEnum
type V1AiImageUpscalercreateResponse401MessageEnum string

const (
	V1AiImageUpscalercreateResponse401MessageEnumUnauthorized V1AiImageUpscalercreateResponse401MessageEnum = "Unauthorized"
)
