package types

// V1AiImageGeneratorCreateBodyOrientationEnum
type V1AiImageGeneratorCreateBodyOrientationEnum string

const (
	V1AiImageGeneratorCreateBodyOrientationEnumLandscape V1AiImageGeneratorCreateBodyOrientationEnum = "landscape"
	V1AiImageGeneratorCreateBodyOrientationEnumPortrait  V1AiImageGeneratorCreateBodyOrientationEnum = "portrait"
	V1AiImageGeneratorCreateBodyOrientationEnumSquare    V1AiImageGeneratorCreateBodyOrientationEnum = "square"
)
