package types

// Language to translate the video's speech into.
type V1AiVideoTranslatorCreateBodyTargetLanguageEnum string

const (
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumAfrikaans          V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Afrikaans"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumArabic             V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Arabic"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumBengali            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Bengali"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumBulgarian          V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Bulgarian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumCatalan            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Catalan"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumChineseSimplified  V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Chinese (Simplified)"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumChineseTraditional V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Chinese (Traditional)"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumCroatian           V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Croatian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumCzech              V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Czech"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumDanish             V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Danish"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumDutch              V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Dutch"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumEnglish            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "English"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumEstonian           V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Estonian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumFinnish            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Finnish"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumFrench             V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "French"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumGerman             V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "German"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumGreek              V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Greek"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumGujarati           V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Gujarati"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumHebrew             V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Hebrew"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumHindi              V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Hindi"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumHungarian          V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Hungarian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumIndonesian         V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Indonesian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumItalian            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Italian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumJapanese           V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Japanese"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumKannada            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Kannada"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumKazakh             V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Kazakh"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumKorean             V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Korean"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumLatvian            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Latvian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumLithuanian         V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Lithuanian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumMalay              V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Malay"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumMalayalam          V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Malayalam"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumMarathi            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Marathi"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumNorwegian          V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Norwegian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumPersian            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Persian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumPolish             V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Polish"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumPortuguese         V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Portuguese"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumPunjabi            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Punjabi"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumRomanian           V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Romanian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumRussian            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Russian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumSerbian            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Serbian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumSlovak             V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Slovak"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumSlovenian          V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Slovenian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumSpanish            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Spanish"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumSwahili            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Swahili"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumSwedish            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Swedish"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumTamil              V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Tamil"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumTelugu             V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Telugu"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumThai               V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Thai"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumTurkish            V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Turkish"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumUkrainian          V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Ukrainian"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumUrdu               V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Urdu"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumVietnamese         V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Vietnamese"
	V1AiVideoTranslatorCreateBodyTargetLanguageEnumWelsh              V1AiVideoTranslatorCreateBodyTargetLanguageEnum = "Welsh"
)
