package types

// V1AiImageGeneratorCreateResponse401MessageEnum
type V1AiImageGeneratorCreateResponse401MessageEnum string

const (
	V1AiImageGeneratorCreateResponse401MessageEnumUnauthorized V1AiImageGeneratorCreateResponse401MessageEnum = "Unauthorized"
)
