package types

// V1AiHeadshotGeneratorCreateResponse401MessageEnum
type V1AiHeadshotGeneratorCreateResponse401MessageEnum string

const (
	V1AiHeadshotGeneratorCreateResponse401MessageEnumUnauthorized V1AiHeadshotGeneratorCreateResponse401MessageEnum = "Unauthorized"
)
