package types

// V1FaceDetectionCreateResponse401MessageEnum
type V1FaceDetectionCreateResponse401MessageEnum string

const (
	V1FaceDetectionCreateResponse401MessageEnumUnauthorized V1FaceDetectionCreateResponse401MessageEnum = "Unauthorized"
)
