package types

// V1ImageProjectsDeleteResponse401MessageEnum
type V1ImageProjectsDeleteResponse401MessageEnum string

const (
	V1ImageProjectsDeleteResponse401MessageEnumUnauthorized V1ImageProjectsDeleteResponse401MessageEnum = "Unauthorized"
)
