package types

// V1ImageBackgroundRemovercreateResponse404MessageEnum
type V1ImageBackgroundRemovercreateResponse404MessageEnum string

const (
	V1ImageBackgroundRemovercreateResponse404MessageEnumNotFound V1ImageBackgroundRemovercreateResponse404MessageEnum = "Not Found"
)
