package types

// V1PhotoColorizerCreateResponse401MessageEnum
type V1PhotoColorizerCreateResponse401MessageEnum string

const (
	V1PhotoColorizerCreateResponse401MessageEnumUnauthorized V1PhotoColorizerCreateResponse401MessageEnum = "Unauthorized"
)
