package types

// V1TextToVideoCreateResponse401MessageEnum
type V1TextToVideoCreateResponse401MessageEnum string

const (
	V1TextToVideoCreateResponse401MessageEnumUnauthorized V1TextToVideoCreateResponse401MessageEnum = "Unauthorized"
)
