package types

// V1VideoToVideoCreateBodyStyleArtStyleEnum
type V1VideoToVideoCreateBodyStyleArtStyleEnum string

const (
	V1VideoToVideoCreateBodyStyleArtStyleEnum3dRender          V1VideoToVideoCreateBodyStyleArtStyleEnum = "3D Render"
	V1VideoToVideoCreateBodyStyleArtStyleEnumAirbender         V1VideoToVideoCreateBodyStyleArtStyleEnum = "Airbender"
	V1VideoToVideoCreateBodyStyleArtStyleEnumAndroid           V1VideoToVideoCreateBodyStyleArtStyleEnum = "Android"
	V1VideoToVideoCreateBodyStyleArtStyleEnumAnimeWarrior      V1VideoToVideoCreateBodyStyleArtStyleEnum = "Anime Warrior"
	V1VideoToVideoCreateBodyStyleArtStyleEnumArmoredKnight     V1VideoToVideoCreateBodyStyleArtStyleEnum = "Armored Knight"
	V1VideoToVideoCreateBodyStyleArtStyleEnumAssassinSCreed    V1VideoToVideoCreateBodyStyleArtStyleEnum = "Assassin's Creed"
	V1VideoToVideoCreateBodyStyleArtStyleEnumAvatar            V1VideoToVideoCreateBodyStyleArtStyleEnum = "Avatar"
	V1VideoToVideoCreateBodyStyleArtStyleEnumBlackSpiderman    V1VideoToVideoCreateBodyStyleArtStyleEnum = "Black Spiderman"
	V1VideoToVideoCreateBodyStyleArtStyleEnumBobaFett          V1VideoToVideoCreateBodyStyleArtStyleEnum = "Boba Fett"
	V1VideoToVideoCreateBodyStyleArtStyleEnumBoldAnime         V1VideoToVideoCreateBodyStyleArtStyleEnum = "Bold Anime"
	V1VideoToVideoCreateBodyStyleArtStyleEnumCelestialSkin     V1VideoToVideoCreateBodyStyleArtStyleEnum = "Celestial Skin"
	V1VideoToVideoCreateBodyStyleArtStyleEnumChineseSwordsmen  V1VideoToVideoCreateBodyStyleArtStyleEnum = "Chinese Swordsmen"
	V1VideoToVideoCreateBodyStyleArtStyleEnumClay              V1VideoToVideoCreateBodyStyleArtStyleEnum = "Clay"
	V1VideoToVideoCreateBodyStyleArtStyleEnumComic             V1VideoToVideoCreateBodyStyleArtStyleEnum = "Comic"
	V1VideoToVideoCreateBodyStyleArtStyleEnumCyberpunk         V1VideoToVideoCreateBodyStyleArtStyleEnum = "Cyberpunk"
	V1VideoToVideoCreateBodyStyleArtStyleEnumCypher            V1VideoToVideoCreateBodyStyleArtStyleEnum = "Cypher"
	V1VideoToVideoCreateBodyStyleArtStyleEnumDarkFantasy       V1VideoToVideoCreateBodyStyleArtStyleEnum = "Dark Fantasy"
	V1VideoToVideoCreateBodyStyleArtStyleEnumDragonballZ       V1VideoToVideoCreateBodyStyleArtStyleEnum = "Dragonball Z"
	V1VideoToVideoCreateBodyStyleArtStyleEnumFutureBot         V1VideoToVideoCreateBodyStyleArtStyleEnum = "Future Bot"
	V1VideoToVideoCreateBodyStyleArtStyleEnumFuturisticFantasy V1VideoToVideoCreateBodyStyleArtStyleEnum = "Futuristic Fantasy"
	V1VideoToVideoCreateBodyStyleArtStyleEnumGta               V1VideoToVideoCreateBodyStyleArtStyleEnum = "GTA"
	V1VideoToVideoCreateBodyStyleArtStyleEnumGhost             V1VideoToVideoCreateBodyStyleArtStyleEnum = "Ghost"
	V1VideoToVideoCreateBodyStyleArtStyleEnumGundam            V1VideoToVideoCreateBodyStyleArtStyleEnum = "Gundam"
	V1VideoToVideoCreateBodyStyleArtStyleEnumHologram          V1VideoToVideoCreateBodyStyleArtStyleEnum = "Hologram"
	V1VideoToVideoCreateBodyStyleArtStyleEnumIllustration      V1VideoToVideoCreateBodyStyleArtStyleEnum = "Illustration"
	V1VideoToVideoCreateBodyStyleArtStyleEnumImpressionism     V1VideoToVideoCreateBodyStyleArtStyleEnum = "Impressionism"
	V1VideoToVideoCreateBodyStyleArtStyleEnumInk               V1VideoToVideoCreateBodyStyleArtStyleEnum = "Ink"
	V1VideoToVideoCreateBodyStyleArtStyleEnumInkPoster         V1VideoToVideoCreateBodyStyleArtStyleEnum = "Ink Poster"
	V1VideoToVideoCreateBodyStyleArtStyleEnumJinx              V1VideoToVideoCreateBodyStyleArtStyleEnum = "Jinx"
	V1VideoToVideoCreateBodyStyleArtStyleEnumKnight            V1VideoToVideoCreateBodyStyleArtStyleEnum = "Knight"
	V1VideoToVideoCreateBodyStyleArtStyleEnumLego              V1VideoToVideoCreateBodyStyleArtStyleEnum = "Lego"
	V1VideoToVideoCreateBodyStyleArtStyleEnumLink              V1VideoToVideoCreateBodyStyleArtStyleEnum = "Link"
	V1VideoToVideoCreateBodyStyleArtStyleEnumMarble            V1VideoToVideoCreateBodyStyleArtStyleEnum = "Marble"
	V1VideoToVideoCreateBodyStyleArtStyleEnumMario             V1VideoToVideoCreateBodyStyleArtStyleEnum = "Mario"
	V1VideoToVideoCreateBodyStyleArtStyleEnumMasterChief       V1VideoToVideoCreateBodyStyleArtStyleEnum = "Master Chief"
	V1VideoToVideoCreateBodyStyleArtStyleEnumMech              V1VideoToVideoCreateBodyStyleArtStyleEnum = "Mech"
	V1VideoToVideoCreateBodyStyleArtStyleEnumMinecraft         V1VideoToVideoCreateBodyStyleArtStyleEnum = "Minecraft"
	V1VideoToVideoCreateBodyStyleArtStyleEnumMystique          V1VideoToVideoCreateBodyStyleArtStyleEnum = "Mystique"
	V1VideoToVideoCreateBodyStyleArtStyleEnumNaruto            V1VideoToVideoCreateBodyStyleArtStyleEnum = "Naruto"
	V1VideoToVideoCreateBodyStyleArtStyleEnumNeonDream         V1VideoToVideoCreateBodyStyleArtStyleEnum = "Neon Dream"
	V1VideoToVideoCreateBodyStyleArtStyleEnumNoArtStyle        V1VideoToVideoCreateBodyStyleArtStyleEnum = "No Art Style"
	V1VideoToVideoCreateBodyStyleArtStyleEnumOilPainting       V1VideoToVideoCreateBodyStyleArtStyleEnum = "Oil Painting"
	V1VideoToVideoCreateBodyStyleArtStyleEnumOnFire            V1VideoToVideoCreateBodyStyleArtStyleEnum = "On Fire"
	V1VideoToVideoCreateBodyStyleArtStyleEnumOrigami           V1VideoToVideoCreateBodyStyleArtStyleEnum = "Origami"
	V1VideoToVideoCreateBodyStyleArtStyleEnumPainterlyAnime    V1VideoToVideoCreateBodyStyleArtStyleEnum = "Painterly Anime"
	V1VideoToVideoCreateBodyStyleArtStyleEnumPixar             V1VideoToVideoCreateBodyStyleArtStyleEnum = "Pixar"
	V1VideoToVideoCreateBodyStyleArtStyleEnumPixel             V1VideoToVideoCreateBodyStyleArtStyleEnum = "Pixel"
	V1VideoToVideoCreateBodyStyleArtStyleEnumPowerArmor        V1VideoToVideoCreateBodyStyleArtStyleEnum = "Power Armor"
	V1VideoToVideoCreateBodyStyleArtStyleEnumPowerRanger       V1VideoToVideoCreateBodyStyleArtStyleEnum = "Power Ranger"
	V1VideoToVideoCreateBodyStyleArtStyleEnumRealisticAnime    V1VideoToVideoCreateBodyStyleArtStyleEnum = "Realistic Anime"
	V1VideoToVideoCreateBodyStyleArtStyleEnumRetroAnime        V1VideoToVideoCreateBodyStyleArtStyleEnum = "Retro Anime"
	V1VideoToVideoCreateBodyStyleArtStyleEnumRetroSciFi        V1VideoToVideoCreateBodyStyleArtStyleEnum = "Retro Sci-Fi"
	V1VideoToVideoCreateBodyStyleArtStyleEnumSamurai           V1VideoToVideoCreateBodyStyleArtStyleEnum = "Samurai"
	V1VideoToVideoCreateBodyStyleArtStyleEnumSamuraiBot        V1VideoToVideoCreateBodyStyleArtStyleEnum = "Samurai Bot"
	V1VideoToVideoCreateBodyStyleArtStyleEnumSolidSnake        V1VideoToVideoCreateBodyStyleArtStyleEnum = "Solid Snake"
	V1VideoToVideoCreateBodyStyleArtStyleEnumSpartan           V1VideoToVideoCreateBodyStyleArtStyleEnum = "Spartan"
	V1VideoToVideoCreateBodyStyleArtStyleEnumStarfield         V1VideoToVideoCreateBodyStyleArtStyleEnum = "Starfield"
	V1VideoToVideoCreateBodyStyleArtStyleEnumStreetFighter     V1VideoToVideoCreateBodyStyleArtStyleEnum = "Street Fighter"
	V1VideoToVideoCreateBodyStyleArtStyleEnumStudioGhibli      V1VideoToVideoCreateBodyStyleArtStyleEnum = "Studio Ghibli"
	V1VideoToVideoCreateBodyStyleArtStyleEnumSubZero           V1VideoToVideoCreateBodyStyleArtStyleEnum = "Sub-Zero"
	V1VideoToVideoCreateBodyStyleArtStyleEnumTheVoid           V1VideoToVideoCreateBodyStyleArtStyleEnum = "The Void"
	V1VideoToVideoCreateBodyStyleArtStyleEnumTombRaider        V1VideoToVideoCreateBodyStyleArtStyleEnum = "Tomb Raider"
	V1VideoToVideoCreateBodyStyleArtStyleEnumUnderwater        V1VideoToVideoCreateBodyStyleArtStyleEnum = "Underwater"
	V1VideoToVideoCreateBodyStyleArtStyleEnumVanGogh           V1VideoToVideoCreateBodyStyleArtStyleEnum = "Van Gogh"
	V1VideoToVideoCreateBodyStyleArtStyleEnumViking            V1VideoToVideoCreateBodyStyleArtStyleEnum = "Viking"
	V1VideoToVideoCreateBodyStyleArtStyleEnumWatercolor        V1VideoToVideoCreateBodyStyleArtStyleEnum = "Watercolor"
	V1VideoToVideoCreateBodyStyleArtStyleEnumWuKong            V1VideoToVideoCreateBodyStyleArtStyleEnum = "Wu Kong"
	V1VideoToVideoCreateBodyStyleArtStyleEnumZelda             V1VideoToVideoCreateBodyStyleArtStyleEnum = "Zelda"
)
