package types

// V1VideoToVideoCreateBodyAssetsVideoSourceEnum
type V1VideoToVideoCreateBodyAssetsVideoSourceEnum string

const (
	V1VideoToVideoCreateBodyAssetsVideoSourceEnumFile    V1VideoToVideoCreateBodyAssetsVideoSourceEnum = "file"
	V1VideoToVideoCreateBodyAssetsVideoSourceEnumYoutube V1VideoToVideoCreateBodyAssetsVideoSourceEnum = "youtube"
)
