// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package animation

import (
	types "github.com/magichourhq/magic-hour-go/types"
)

// CreateRequest
type CreateRequest struct {
	Data types.PostV1AnimationBody `json:"data"`
}
