// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package image_background_remover

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
	types "github.com/magichourhq/magic-hour-go/types"
)

// CreateRequest
type CreateRequest struct {
	// Provide the assets for background removal
	Assets types.PostV1ImageBackgroundRemoverBodyAssets `json:"assets"`
	// The name of image
	Name nullable.Nullable[string] `json:"name,omitempty"`
}
