// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package ai_photo_editor

import (
	types "github.com/magichourhq/magic-hour-go/types"
)

// CreateRequest
type CreateRequest struct {
	Data types.PostV1AiPhotoEditorBody `json:"data"`
}
