// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package face_swap_photo

import (
	types "github.com/magichourhq/magic-hour-go/types"
)

// CreateRequest
type CreateRequest struct {
	Data types.PostV1FaceSwapPhotoBody `json:"data"`
}
