// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package face_swap_photo

import (
	nullable "github.com/magichourhq/magic-hour-go/nullable"
	types "github.com/magichourhq/magic-hour-go/types"
)

// CreateRequest
type CreateRequest struct {
	// Provide the assets for face swap photo
	Assets types.PostV1FaceSwapPhotoBodyAssets `json:"assets"`
	// The name of image
	Name nullable.Nullable[string] `json:"name,omitempty"`
}
