// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package text_to_video

import (
	types "github.com/magichourhq/magic-hour-go/types"
)

// CreateRequest
type CreateRequest struct {
	Data types.PostV1TextToVideoBody `json:"data"`
}
