// Code generated by Sideko (sideko.dev) DO NOT EDIT.

package ai_headshot_generator

import (
	types "github.com/magichourhq/magic-hour-go/types"
)

// CreateRequest
type CreateRequest struct {
	Data types.PostV1AiHeadshotGeneratorBody `json:"data"`
}
